# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'
    versioning-strategy: increase
    groups:
      dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
