import type { ESLint, Linter } from 'eslint'
// @ts-expect-error -- no types
import pluginUnicorn from 'eslint-plugin-unicorn'

export function unicorn(): Linter.FlatConfig[] {
  return [
    {
      plugins: {
        unicorn: pluginUnicorn as ESLint.Plugin,
      },
      rules: {
        // This rule is superseded by the unicorn version below
        'no-nested-ternary': 'off',
        'unicorn/better-regex': 'warn',
        'unicorn/catch-error-name': 'error',
        'unicorn/consistent-destructuring': 'warn',
        'unicorn/consistent-function-scoping': [
          'error',
          { checkArrowFunctions: false },
        ],
        'unicorn/custom-error-definition': 'warn',
        'unicorn/empty-brace-spaces': 'warn',
        'unicorn/error-message': 'error',
        'unicorn/escape-case': 'warn',
        'unicorn/expiring-todo-comments': 'error',
        // Don't care how if(blah.length) is checked
        'unicorn/explicit-length-check': 'off',
        'unicorn/filename-case': 'error',
        'unicorn/import-index': ['warn', { ignoreImports: true }],
        // TODO Not sure if this is useful yet
        'unicorn/import-style': 'off',
        'unicorn/new-for-builtins': 'warn',
        'unicorn/no-abusive-eslint-disable': 'error',
        'unicorn/no-array-callback-reference': 'off',
        'unicorn/no-array-for-each': 'warn',
        'unicorn/no-array-method-this-argument': 'warn',
        'unicorn/no-array-push-push': 'warn',
        'unicorn/no-array-reduce': 'error',
        'unicorn/no-await-expression-member': 'warn',
        'unicorn/no-console-spaces': 'warn',
        'unicorn/no-document-cookie': 'error',
        // TODO turn back on when it can exclude files. As this warns about the
        // auto-generated next-env.d.ts file.
        'unicorn/no-empty-file': 'off',
        'unicorn/no-for-loop': 'warn',
        'unicorn/no-hex-escape': 'warn',
        'unicorn/no-instanceof-array': 'warn',
        'unicorn/no-invalid-remove-event-listener': 'error',
        'unicorn/no-keyword-prefix': [
          'error',
          {
            // Do not check properties and allow "class" so that "className" is
            // allowed.
            checkProperties: false,
            disallowedPrefixes: ['new'],
          },
        ],
        'unicorn/no-lonely-if': 'warn',
        'unicorn/no-negated-condition': 'warn',
        'unicorn/no-nested-ternary': 'off',
        'unicorn/no-new-array': 'warn',
        'unicorn/no-new-buffer': 'warn',
        'unicorn/no-null': 'off',
        'unicorn/no-object-as-default-parameter': 'error',
        'unicorn/no-process-exit': 'error',
        'unicorn/no-static-only-class': 'error',
        'unicorn/no-thenable': 'error',
        'unicorn/no-this-assignment': 'error',
        'unicorn/no-typeof-undefined': 'warn',
        'unicorn/no-unnecessary-await': 'warn',
        'unicorn/no-unnecessary-polyfills': 'error',
        'unicorn/no-unreadable-array-destructuring': 'error',
        'unicorn/no-unreadable-iife': 'error',
        // Turned off for now, even Sindre doesn't like it:
        // https://github.com/sindresorhus/eslint-plugin-unicorn/issues/153
        'unicorn/no-unsafe-regex': 'off',
        // Recommended config turned this off so I will too
        'unicorn/no-unused-properties': 'off',
        'unicorn/no-useless-fallback-in-spread': 'warn',
        'unicorn/no-useless-length-check': 'warn',
        'unicorn/no-useless-promise-resolve-reject': 'warn',
        'unicorn/no-useless-spread': 'warn',
        'unicorn/no-useless-switch-case': 'error',
        'unicorn/no-useless-undefined': 'warn',
        'unicorn/no-zero-fractions': 'warn',
        'unicorn/number-literal-case': 'warn',
        'unicorn/numeric-separators-style': 'warn',
        'unicorn/prefer-add-event-listener': 'warn',
        'unicorn/prefer-array-find': 'warn',
        'unicorn/prefer-array-flat': 'warn',
        'unicorn/prefer-array-flat-map': 'warn',
        'unicorn/prefer-array-index-of': 'warn',
        'unicorn/prefer-array-some': 'error',
        'unicorn/prefer-at': 'warn',
        'unicorn/prefer-blob-reading-methods': 'error',
        'unicorn/prefer-code-point': 'error',
        'unicorn/prefer-date-now': 'warn',
        'unicorn/prefer-default-parameters': 'warn',
        'unicorn/prefer-dom-node-append': 'warn',
        'unicorn/prefer-dom-node-dataset': 'warn',
        'unicorn/prefer-dom-node-remove': 'warn',
        'unicorn/prefer-dom-node-text-content': 'warn',
        'unicorn/prefer-event-target': 'error',
        'unicorn/prefer-export-from': 'warn',
        'unicorn/prefer-includes': 'warn',
        'unicorn/prefer-json-parse-buffer': 'warn',
        'unicorn/prefer-keyboard-event-key': 'warn',
        'unicorn/prefer-logical-operator-over-ternary': 'warn',
        'unicorn/prefer-math-trunc': 'warn',
        'unicorn/prefer-modern-dom-apis': 'warn',
        'unicorn/prefer-modern-math-apis': 'warn',
        // Not ready yet for ESM modules
        // https://github.com/microsoft/TypeScript/issues/33079
        'unicorn/prefer-module': 'warn',
        'unicorn/prefer-native-coercion-functions': 'warn',
        'unicorn/prefer-negative-index': 'warn',
        // TODO seems like this is not well supported by webpack yet
        'unicorn/prefer-node-protocol': 'off',
        'unicorn/prefer-number-properties': 'warn',
        'unicorn/prefer-object-from-entries': 'warn',
        'unicorn/prefer-object-has-own': 'warn',
        'unicorn/prefer-optional-catch-binding': 'warn',
        'unicorn/prefer-prototype-methods': 'warn',
        'unicorn/prefer-query-selector': 'warn',
        'unicorn/prefer-reflect-apply': 'warn',
        'unicorn/prefer-regexp-test': 'warn',
        'unicorn/prefer-set-has': 'warn',
        'unicorn/prefer-set-size': 'warn',
        'unicorn/prefer-spread': 'warn',
        'unicorn/prefer-string-replace-all': 'warn',
        'unicorn/prefer-string-slice': 'warn',
        'unicorn/prefer-string-starts-ends-with': 'error',
        'unicorn/prefer-string-trim-start-end': 'warn',
        'unicorn/prefer-switch': 'off',
        'unicorn/prefer-ternary': ['warn', 'only-single-line'],
        'unicorn/prefer-top-level-await': 'error',
        'unicorn/prefer-type-error': 'warn',
        'unicorn/prevent-abbreviations': 'off',
        'unicorn/regex-shorthand': 'warn',
        'unicorn/relative-url-style': 'warn',
        'unicorn/require-array-join-separator': 'warn',
        'unicorn/require-number-to-fixed-digits-argument': 'warn',
        'unicorn/require-post-message-target-origin': 'error',
        'unicorn/string-content': 'off',
        'unicorn/switch-case-braces': ['warn', 'avoid'],
        'unicorn/template-indent': [
          'warn',
          {
            indent: 2,
          },
        ],
        'unicorn/text-encoding-identifier-case': 'error',
        'unicorn/throw-new-error': 'warn',
      },
    },
  ]
}
